name: frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (not really needed, but keeps Actions happy)
        uses: actions/checkout@v3

      - name: Deploy and build on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /var/www/frontend
            echo "Pulling latest changes..."
            git pull origin main

            echo "Installing dependencies..."
            npm install --production

            echo "Building project..."
            npm run build

            echo "Restarting nginx..."
            sudo systemctl restart nginx
