- name: Deploy and build on server
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.LIGHTSAIL_HOST }}
    username: ${{ secrets.LIGHTSAIL_USERNAME }}
    key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
    script: |
      cd /var/www/frontend
      git config --global --add safe.directory /var/www/frontend
      sudo chown -R $USER:$USER /var/www/frontend

      # Upgrade Node.js to v20 if needed
      if ! node -v | grep -q "v20"; then
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
        sudo apt-get install -y nodejs
      fi

      git pull origin main
      npm install
      npm run build

      sudo systemctl restart nginx
