name: Deploy React Frontend to AWS Lightsail

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Changed from 22 to 18 for better stability

      - name: Install and Build
        run: |
          npm ci           # Using ci instead of install for reproducible builds
          npm run build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd /var/www/htmlsite/firstexam/frontend
            git pull origin main
            npm ci --production
            npm run build
            sudo rm -rf /var/www/htmlsite/firstexam/frontend/dist/*
            sudo cp -r dist/* /var/www/htmlsite/firstexam/frontend/dist/
            sudo systemctl restart nginx