name: Deploy React Frontend to AWS Lightsail

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Create tarball of dist folder
        run: |
          tar -czf dist.tar.gz -C dist .

      - name: Upload dist.tar.gz to Lightsail server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "dist.tar.gz"
          target: "/tmp"

      - name: Extract tarball on server without changing ownership or permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/new/frontend
            sudo tar --no-same-owner --no-same-permissions --no-mtime -xzf /tmp/dist.tar.gz -C /var/www/new/frontend
            sudo rm /tmp/dist.tar.gz

      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
